"""make_approver_id_nullable

Revision ID: a0d8a1364284
Revises: 71b57508efeb
Create Date: 2025-10-24 18:24:19.795842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d8a1364284'
down_revision = '71b57508efeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approvals', 'approver_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approvals', 'approver_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
